name: CI Deploy to Production
on:
  workflow_dispatch:

jobs:
  test:
    name: Test and Lint
    uses: paulAlexSerban/fe--ui-techstack-insights/.github/workflows/ci-development.yml@main

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      # Checkout repository
      - name: "â˜ï¸ checkout repository"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Cache node_modules to speed up things
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      # Install NodeJS & npm
      - name: "ğŸ”§ Setup NodeJS 14.19.1"
        uses: actions/setup-node@v1
        with:
          node-version: 14.19.1

      - name: "ğŸ”§ Install npm@latest"
        run: npm i -g npm@latest

      # Install ./assets dependencies

      # Install ./frontend/static/poc dependencies
      - name: "ğŸ“¦  Install Static Proof Of Concept dependencies"
        run: npm --prefix frontend/static/poc install

      # Build ./assets

      # Build ./frontend/static/poc
      - name: "ğŸ—ï¸  Build static/poc project"
        run: npm run build:frontend:poc

      # Package ./frontend/static/poc
      - name: "ğŸ“¦ Package static/poc"
        run: "npm run package:static:poc"

      # Deploy ./frontend/static/poc to GitHub pages
      - name: Deploy static/poc to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages-static-poc
          folder: docs/static/poc

